<?php
/**
 * Generates squid.conf from structured data
 */
class SquidConfigBuilder {
    private $config = [];

    public function loadFromDatabase() {
        $this->config['acls'] = Database::fetchAll("SELECT * FROM acls ORDER BY name, id");
        $this->config['http_access'] = Database::fetchAll("SELECT * FROM http_access_rules ORDER BY sort_order, id");
        $this->config['peers'] = Database::fetchAll("SELECT * FROM cache_peers ORDER BY id");
        $this->config['auth'] = Database::fetchAll("SELECT * FROM auth_config ORDER BY id");
        $this->config['ext_acl'] = Database::fetchAll("SELECT * FROM external_acl_types ORDER BY name, id");
        $this->config['globals'] = Database::fetch("SELECT * FROM squid_globals LIMIT 1") ?: [];
        return $this;
    }

    public function generate() {
        $lines = [];
        $lines[] = "# Generated by Squid Proxy Manager v" . SPM_VERSION;
        $lines[] = "# Do not edit manually — changes will be overwritten";
        $lines[] = "# Generated: " . date('Y-m-d H:i:s');
        $lines[] = "";

        // Global settings
        $globals = $this->config['globals'];
        if (!empty($globals)) {
            $lines[] = "# === Global Settings ===";
            if (!empty($globals['http_port'])) $lines[] = "http_port " . $globals['http_port'];
            if (!empty($globals['icp_port'])) $lines[] = "icp_port " . $globals['icp_port'];
            if (!empty($globals['cache_dir'])) $lines[] = "cache_dir " . $globals['cache_dir'];
            if (!empty($globals['visible_hostname'])) $lines[] = "visible_hostname " . $globals['visible_hostname'];
            if (!empty($globals['dns_nameservers'])) $lines[] = "dns_nameservers " . $globals['dns_nameservers'];
            $lines[] = "";
        }

        // Authentication
        if (!empty($this->config['auth'])) {
            $lines[] = "# === Authentication ===";
            foreach ($this->config['auth'] as $auth) {
                $scheme = $auth['scheme'] ?? '';
                $program = trim($auth['program'] ?? '');
                if ($program === '') {
                    continue;
                }
                $children = (int)($auth['children'] ?: 5);
                $childrenLine = (string)($children ?: ($scheme === 'negotiate' || $scheme === 'ntlm' ? 10 : 5));
                $extra = trim((string)($auth['children_extra'] ?? ''));
                if ($extra !== '') {
                    $childrenLine .= ' ' . $extra;
                }
                if ($scheme === 'basic') {
                    $lines[] = "auth_param basic program " . $program;
                    $lines[] = "auth_param basic children " . $childrenLine;
                    $lines[] = "auth_param basic realm " . ($auth['realm'] ?: 'Squid Proxy');
                    $lines[] = "auth_param basic credentialsttl " . ($auth['credentialsttl'] ?: '2 hours');
                } elseif ($scheme === 'negotiate') {
                    $lines[] = "auth_param negotiate program " . $program;
                    $lines[] = "auth_param negotiate children " . $childrenLine;
                    $lines[] = "auth_param negotiate keep_alive " . ($auth['keep_alive'] ?: 'on');
                } elseif ($scheme === 'ntlm') {
                    $lines[] = "auth_param ntlm program " . $program;
                    $lines[] = "auth_param ntlm children " . $childrenLine;
                } elseif ($scheme === 'digest') {
                    $lines[] = "auth_param digest program " . $program;
                    $lines[] = "auth_param digest children " . $childrenLine;
                    if (!empty($auth['realm'])) {
                        $lines[] = "auth_param digest realm " . $auth['realm'];
                    }
                }
            }
            $lines[] = "";
        }

        if (!empty($this->config['ext_acl'])) {
            $lines[] = "# === External ACL helpers ===";
            foreach ($this->config['ext_acl'] as $ext) {
                $name = trim((string)($ext['name'] ?? ''));
                $program = trim((string)($ext['program'] ?? ''));
                if ($name === '' || $program === '') {
                    continue;
                }
                $line = 'external_acl_type ' . $name;
                $ttl = (int)($ext['ttl'] ?? 3600);
                $neg = (int)($ext['negative_ttl'] ?? 60);
                $children = (int)($ext['children'] ?? 10);
                if ($ttl > 0) {
                    $line .= ' ttl=' . $ttl;
                }
                if ($neg > 0) {
                    $line .= ' negative_ttl=' . $neg;
                }
                if ($children > 0) {
                    $line .= ' children=' . $children;
                }
                $format = trim((string)($ext['format'] ?? '%LOGIN'));
                if ($format === '') {
                    $format = '%LOGIN';
                }
                $line .= ' ' . $format . ' ' . $program;
                $opts = trim((string)($ext['options'] ?? ''));
                if ($opts !== '') {
                    $line .= ' ' . $opts;
                }
                $lines[] = $line;
            }
            $lines[] = "";
        }

        // ACLs
        $lines[] = "# === ACL Definitions ===";
        foreach ($this->config['acls'] as $acl) {
            $name = $acl['name'];
            $type = $acl['type'];
            if (($acl['storage'] ?? 'inline') === 'file') {
                $lines[] = "acl " . $name . " " . $type . " " . AclListFile::squidRef($name);
                continue;
            }
            $values = json_decode($acl['entries'], true) ?: [];
            if ($type === 'external') {
                if (empty($values)) {
                    continue;
                }
                $quoted = [];
                foreach ($values as $val) {
                    $quoted[] = $this->quoteAclToken((string)$val);
                }
                $lines[] = 'acl ' . $name . ' external ' . implode(' ', $quoted);
                continue;
            }
            foreach ($values as $val) {
                $lines[] = "acl " . $name . " " . $type . " " . $this->quoteAclToken((string)$val);
            }
        }
        $lines[] = "";

        // Cache Peers
        if (!empty($this->config['peers'])) {
            $lines[] = "# === Cache Peers ===";
            foreach ($this->config['peers'] as $peer) {
                if (($peer['status'] ?? 'active') === 'disabled') {
                    continue;
                }
                $httpPort = $peer['http_port'] ?? $peer['port'] ?? 3128;
                $icpPort = $peer['icp_port'] ?? 0;
                $line = "cache_peer " . $peer['hostname'] . " " . $peer['peer_type'] . " " . $httpPort . " " . (int)$icpPort;
                $options = [];
                $seen = [];
                $addOpt = function ($token) use (&$options, &$seen) {
                    $token = trim((string)$token);
                    if ($token === '' || isset($seen[$token])) {
                        return;
                    }
                    $seen[$token] = true;
                    $options[] = $token;
                };
                if (!empty($peer['proxy_only'])) $addOpt('proxy-only');
                if (!empty($peer['no_query'])) $addOpt('no-query');
                if (!empty($peer['no_digest'])) $addOpt('no-digest');
                if (!empty($peer['weight'])) $addOpt('weight=' . $peer['weight']);
                if (!empty($peer['login'])) $addOpt('login=' . $peer['login']);
                if (!empty($peer['connect_timeout'])) $addOpt('connect-timeout=' . $peer['connect_timeout']);
                $peerName = trim($peer['name'] ?? '');
                if ($peerName !== '') $addOpt('name=' . $peerName);
                foreach (preg_split('/\s+/', trim((string)($peer['options'] ?? ''))) as $extra) {
                    if (strpos($extra, 'name=') === 0) {
                        continue;
                    }
                    $addOpt($extra);
                }
                if (!empty($options)) $line .= " " . implode(' ', $options);
                $lines[] = $line;
            }
            $lines[] = "";

            // Peer Access Rules — cache_peer_access
            $peerAccessRules = Database::fetchAll(
                "SELECT cpar.*, cp.hostname AS peer_host, cp.name AS peer_name
                 FROM cache_peer_access_rules cpar
                 JOIN cache_peers cp ON cpar.peer_id = cp.id
                 WHERE COALESCE(cp.status, 'active') = 'active'
                 ORDER BY cp.id, cpar.sort_order, cpar.id"
            );

            if (!empty($peerAccessRules)) {
                $lines[] = "# === Cache Peer Access Rules ===";
                foreach ($peerAccessRules as $rule) {
                    $peerRef = trim((string)($rule['peer_name'] ?? ''));
                    if ($peerRef === '') {
                        $peerRef = $rule['hostname'] ?: $rule['peer_host'];
                    }
                    $acls = trim((string)($rule['acl_entries'] !== '' ? $rule['acl_entries'] : $rule['acl_name']));
                    $lines[] = "cache_peer_access " . $peerRef . " " . $rule['action'] . " " . $acls;
                }
                $lines[] = "";
            }
        }

        // Global Routing directives
        $lines[] = "# === Global Routing ===";
        $routing = Database::fetchAll("SELECT * FROM routing_rules ORDER BY sort_order, id");
        foreach ($routing as $rule) {
            $acl = $rule['acl_name'] ?? '';
            if (($rule['negated'] ?? 0) && strpos($acl, ' ') === false && strpos($acl, '!') !== 0) {
                $acl = '!' . $acl;
            }
            $lines[] = $rule['directive'] . " " . $rule['action'] . " " . $acl;
        }
        $lines[] = "";

        // HTTP Access
        $lines[] = "# === HTTP Access Rules ===";
        foreach ($this->config['http_access'] as $rule) {
            if (isset($rule['enabled']) && (int)$rule['enabled'] === 0) {
                continue;
            }
            $acls = json_decode($rule['acls'], true) ?: [];
            $line = "http_access " . $rule['action'] . " " . implode(' ', $acls);
            $lines[] = $line;
        }
        $lines[] = "http_access deny all";
        $lines[] = "";

        return implode("
", $lines);
    }

    private function quoteAclToken($val) {
        $val = trim($val);
        if ($val === '' || strpos($val, '"') !== false) {
            return $val;
        }
        if (strpbrk($val, " \t") !== false) {
            return '"' . $val . '"';
        }
        return $val;
    }

    public function save($content = null) {
        throw new Exception(
            'Refusing to overwrite live squid.conf. The panel generator is a partial preview and is not applied to CentOS Squid.'
        );
    }
}
