<?php
/**
 * Generates squid.conf from structured data
 */
class SquidConfigBuilder {
    private $config = [];

    public function loadFromDatabase() {
        $this->config['acls'] = Database::fetchAll("SELECT * FROM acls ORDER BY name, id");
        $this->config['http_access'] = Database::fetchAll("SELECT * FROM http_access_rules ORDER BY sort_order, id");
        $this->config['peers'] = Database::fetchAll("SELECT * FROM cache_peers ORDER BY id");
        $this->config['auth'] = Database::fetch("SELECT * FROM auth_config LIMIT 1") ?: [];
        $this->config['globals'] = Database::fetch("SELECT * FROM squid_globals LIMIT 1") ?: [];
        return $this;
    }

    public function generate() {
        $lines = [];
        $lines[] = "# Generated by Squid Proxy Manager v" . SPM_VERSION;
        $lines[] = "# Do not edit manually — changes will be overwritten";
        $lines[] = "# Generated: " . date('Y-m-d H:i:s');
        $lines[] = "";

        // Global settings
        $globals = $this->config['globals'];
        if (!empty($globals)) {
            $lines[] = "# === Global Settings ===";
            if (!empty($globals['http_port'])) $lines[] = "http_port " . $globals['http_port'];
            if (!empty($globals['icp_port'])) $lines[] = "icp_port " . $globals['icp_port'];
            if (!empty($globals['cache_dir'])) $lines[] = "cache_dir " . $globals['cache_dir'];
            if (!empty($globals['visible_hostname'])) $lines[] = "visible_hostname " . $globals['visible_hostname'];
            if (!empty($globals['dns_nameservers'])) $lines[] = "dns_nameservers " . $globals['dns_nameservers'];
            $lines[] = "";
        }

        // Authentication
        if (!empty($this->config['auth'])) {
            $lines[] = "# === Authentication ===";
            $auth = $this->config['auth'];
            if ($auth['scheme'] === 'basic' && !empty($auth['basic_program'])) {
                $lines[] = "auth_param basic program " . $auth['basic_program'];
                $lines[] = "auth_param basic children " . ($auth['children'] ?: 5);
                $lines[] = "auth_param basic realm " . ($auth['realm'] ?: 'Squid Proxy');
                $lines[] = "auth_param basic credentialsttl " . ($auth['credentialsttl'] ?: '2 hours');
            } elseif ($auth['scheme'] === 'negotiate' && !empty($auth['negotiate_program'])) {
                $lines[] = "auth_param negotiate program " . $auth['negotiate_program'];
                $lines[] = "auth_param negotiate children " . ($auth['children'] ?: 10);
                $lines[] = "auth_param negotiate keep_alive " . ($auth['keep_alive'] ?: 'on');
            } elseif ($auth['scheme'] === 'ntlm' && !empty($auth['ntlm_program'])) {
                $lines[] = "auth_param ntlm program " . $auth['ntlm_program'];
                $lines[] = "auth_param ntlm children " . ($auth['children'] ?: 10);
            }
            $lines[] = "";
        }

        // ACLs
        $lines[] = "# === ACL Definitions ===";
        foreach ($this->config['acls'] as $acl) {
            $values = json_decode($acl['entries'], true) ?: [];
            foreach ($values as $val) {
                $lines[] = "acl " . $acl['name'] . " " . $acl['type'] . " " . $val;
            }
        }
        $lines[] = "";

        // Cache Peers
        if (!empty($this->config['peers'])) {
            $lines[] = "# === Cache Peers ===";
            foreach ($this->config['peers'] as $peer) {
                $line = "cache_peer " . $peer['hostname'] . " " . $peer['peer_type'] . " " . $peer['http_port'];
                if ($peer['icp_port']) $line .= " " . $peer['icp_port'];
                $options = [];
                if ($peer['proxy_only']) $options[] = 'proxy-only';
                if ($peer['no_query']) $options[] = 'no-query';
                if ($peer['no_digest']) $options[] = 'no-digest';
                if ($peer['weight']) $options[] = 'weight=' . $peer['weight'];
                if ($peer['login']) $options[] = 'login=' . $peer['login'];
                if ($peer['connect_timeout']) $options[] = 'connect-timeout=' . $peer['connect_timeout'];
                if (!empty($options)) $line .= " " . implode(' ', $options);
                $lines[] = $line;
            }
            $lines[] = "";

            // Peer Access Rules — cache_peer_access
            $peerAccessRules = Database::fetchAll(
                "SELECT cpar.*, cp.hostname FROM cache_peer_access_rules cpar 
                 JOIN cache_peers cp ON cpar.peer_id = cp.id 
                 ORDER BY cp.id, cpar.sort_order, cpar.id"
            );

            if (!empty($peerAccessRules)) {
                $lines[] = "# === Cache Peer Access Rules ===";
                foreach ($peerAccessRules as $rule) {
                    $lines[] = "cache_peer_access " . $rule['hostname'] . " " . $rule['action'] . " " . $rule['acl_name'];
                }
                $lines[] = "";
            }
        }

        // Global Routing directives
        $lines[] = "# === Global Routing ===";
        $routing = Database::fetchAll("SELECT * FROM routing_rules ORDER BY id");
        foreach ($routing as $rule) {
            $lines[] = $rule['directive'] . " " . $rule['action'] . " " . $rule['acl_name'];
        }
        $lines[] = "";

        // HTTP Access
        $lines[] = "# === HTTP Access Rules ===";
        foreach ($this->config['http_access'] as $rule) {
            $acls = json_decode($rule['acls'], true) ?: [];
            $line = "http_access " . $rule['action'] . " " . implode(' ', $acls);
            $lines[] = $line;
        }
        $lines[] = "http_access deny all";
        $lines[] = "";

        return implode("
", $lines);
    }

    public function save($content = null) {
        if ($content === null) {
            $content = $this->generate();
        }

        $backupPath = SQUID_CONF . '.bak.' . date('YmdHis');
        if (file_exists(SQUID_CONF)) {
            copy(SQUID_CONF, $backupPath);
        }

        $newPath = SQUID_CONF . '.new';
        file_put_contents($newPath, $content, LOCK_EX);

        // Validate syntax
        $result = SquidSyntaxChecker::validateFile($newPath);
        if (!$result['valid']) {
            unlink($newPath);
            throw new Exception("Syntax error: " . $result['error']);
        }

        // Atomically replace
        rename($newPath, SQUID_CONF);
        chmod(SQUID_CONF, 0644);
        chown(SQUID_CONF, 'root:root');

        return ['success' => true, 'backup' => $backupPath];
    }
}
