#!/bin/bash
# Squid Proxy Manager — Uninstallation Script
# Removes SPM panel while preserving Squid installation

set -e

SPM_DIR="/opt/spm"
WEB_USER="squidmgr"
NGINX_SPM_CONF="/etc/nginx/conf.d/spm.conf"
SQUID_CONF="/etc/squid/squid.conf"

echo "=== Squid Proxy Manager Uninstaller ==="
echo ""

# Check root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Please run as root"
    exit 1
fi

# Confirm uninstallation
echo "WARNING: This will completely remove Squid Proxy Manager."
echo "  - SPM web panel and database"
echo "  - Nginx configuration for SPM"
echo "  - Privileged agent (spmd)"
echo "  - Sudo rules for SPM"
echo ""
echo "Squid proxy server will NOT be removed."
echo ""
read -p "Are you sure you want to uninstall SPM? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Uninstallation cancelled."
    exit 0
fi

echo ""
echo "[1/7] Stopping SPM services..."
systemctl stop spmd 2>/dev/null || true
systemctl disable spmd 2>/dev/null || true

echo "[2/7] Removing systemd service..."
rm -f /etc/systemd/system/spmd.service
systemctl daemon-reload 2>/dev/null || true

echo "[3/7] Removing Nginx configuration..."
rm -f "$NGINX_SPM_CONF"

# Reload nginx to apply changes (don't stop if other sites exist)
if systemctl list-unit-files | grep -q '^nginx.service'; then
    if systemctl is-active nginx &>/dev/null; then
        if nginx -t 2>/dev/null; then
            systemctl reload nginx 2>/dev/null || systemctl restart nginx
        else
            echo "WARNING: Nginx config test failed after removing SPM config."
            echo "You may need to manually fix /etc/nginx/conf.d/ configuration."
        fi
    fi
else
    echo "INFO: nginx.service not found, skipping nginx reload."
fi

echo "[4/7] Removing PHP-FPM pool..."
rm -f /etc/php-fpm.d/spm.conf

# Reload php-fpm to apply changes
PHP_FPM_SERVICE="php-fpm"
if systemctl list-unit-files | grep -qE '^php[0-9]+\.[0-9]+-fpm\.service'; then
    PHP_FPM_SERVICE=$(systemctl list-unit-files | grep "^php[0-9]\+\.[0-9]\+-fpm\.service" | head -1 | awk '{print $1}' | sed 's/\.service$//')
fi
systemctl reload "$PHP_FPM_SERVICE" 2>/dev/null || true

echo "[5/7] Removing sudoers rules..."
rm -f /etc/sudoers.d/spm

echo "[6/7] Restoring squid.conf from backup (if available)..."
LATEST_BACKUP=$(ls -t ${SQUID_CONF}.bak.* 2>/dev/null | head -1)
if [ -n "$LATEST_BACKUP" ] && [ -f "$LATEST_BACKUP" ]; then
    echo "Found backup: $LATEST_BACKUP"
    read -p "Restore squid.conf from this backup? (yes/no): " RESTORE
    if [ "$RESTORE" = "yes" ]; then
        cp "$LATEST_BACKUP" "$SQUID_CONF"
        chown root:squid "$SQUID_CONF"
        chmod 644 "$SQUID_CONF"
        echo "squid.conf restored from backup."
    fi
else
    echo "No backup found. Current squid.conf will be preserved."
fi

echo "[7/7] Removing SPM files..."
if [ -d "$SPM_DIR" ]; then
    rm -rf "$SPM_DIR"
    echo "Removed $SPM_DIR"
fi

# Remove SSL certificates generated by SPM
rm -f /etc/pki/tls/certs/spm-selfsigned.crt
rm -f /etc/pki/tls/private/spm-selfsigned.key

# Remove socket
rm -f /run/spmd.sock
rm -f /run/spmd.pid
rm -f /run/php-fpm/spm.sock

# Ask about removing user
read -p "Remove system user '$WEB_USER'? (yes/no): " REMOVE_USER
if [ "$REMOVE_USER" = "yes" ]; then
    userdel "$WEB_USER" 2>/dev/null || true
    echo "User '$WEB_USER' removed."
fi

echo ""
echo "=== Uninstallation Complete ==="
echo ""
echo "SPM has been removed. Squid remains installed and configured."
echo ""
echo "To fully remove remaining dependencies (optional):"
echo "  dnf remove nginx php-fpm php-pdo php-sqlite3"
echo ""
echo "To restart Squid if needed:"
echo "  systemctl restart squid"
echo ""
